# Form implementation generated from reading ui file 'widget_settings.ui'
#
# Modified for i18n support and layout changes.


from PyQt6 import QtCore, QtGui, QtWidgets
from ntfy_tray.i18n import tr


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(452, 693)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setObjectName("tabWidget")

        # ── General Tab ──
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # Interface group
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_general)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Language selector
        self.horizontalLayout_lang = QtWidgets.QHBoxLayout()
        self.horizontalLayout_lang.setObjectName("horizontalLayout_lang")
        self.label_language = QtWidgets.QLabel(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_language.sizePolicy().hasHeightForWidth())
        self.label_language.setSizePolicy(sizePolicy)
        self.label_language.setObjectName("label_language")
        self.horizontalLayout_lang.addWidget(self.label_language)
        self.combo_language = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.combo_language.setObjectName("combo_language")
        self.horizontalLayout_lang.addWidget(self.combo_language)
        spacerItem_lang = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_lang.addItem(spacerItem_lang)
        self.verticalLayout_2.addLayout(self.horizontalLayout_lang)

        # Application style selector
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.combo_style = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.combo_style.setObjectName("combo_style")
        self.horizontalLayout_7.addWidget(self.combo_style)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.cb_priority_colors = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.cb_priority_colors.setObjectName("cb_priority_colors")
        self.verticalLayout_2.addWidget(self.cb_priority_colors)
        self.cb_image_urls = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.cb_image_urls.setObjectName("cb_image_urls")
        self.verticalLayout_2.addWidget(self.cb_image_urls)
        self.cb_locale = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.cb_locale.setObjectName("cb_locale")
        self.verticalLayout_2.addWidget(self.cb_locale)
        self.cb_sort_applications = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.cb_sort_applications.setObjectName("cb_sort_applications")
        self.verticalLayout_2.addWidget(self.cb_sort_applications)
        self.cb_autostart = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.cb_autostart.setObjectName("cb_autostart")
        self.verticalLayout_2.addWidget(self.cb_autostart)
        self.verticalLayout_4.addWidget(self.groupBox_2)

        # Server info group
        self.groupBox_server_info = QtWidgets.QGroupBox(parent=self.tab_general)
        self.groupBox_server_info.setObjectName("groupBox_server_info")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_server_info)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_change_server_info = QtWidgets.QPushButton(parent=self.groupBox_server_info)
        self.pb_change_server_info.setObjectName("pb_change_server_info")
        self.gridLayout_3.addWidget(self.pb_change_server_info, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_server_info)

        # Topics API group
        self.groupBox_topics_api = QtWidgets.QGroupBox(parent=self.tab_general)
        self.groupBox_topics_api.setObjectName("groupBox_topics_api")
        self.gridLayout_topics = QtWidgets.QGridLayout(self.groupBox_topics_api)
        self.gridLayout_topics.setObjectName("gridLayout_topics")
        self.line_topics_url = QtWidgets.QLineEdit(parent=self.groupBox_topics_api)
        self.line_topics_url.setObjectName("line_topics_url")
        self.gridLayout_topics.addWidget(self.line_topics_url, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_topics_api)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_general, "")

        # ── Fonts Tab ──
        self.tab_fonts = QtWidgets.QWidget()
        self.tab_fonts.setObjectName("tab_fonts")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_fonts)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_reset_fonts = QtWidgets.QPushButton(parent=self.tab_fonts)
        self.pb_reset_fonts.setObjectName("pb_reset_fonts")
        self.horizontalLayout_5.addWidget(self.pb_reset_fonts)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.groupBox_fonts_message = QtWidgets.QGroupBox(parent=self.tab_fonts)
        self.groupBox_fonts_message.setObjectName("groupBox_fonts_message")
        self.layout_fonts_message = QtWidgets.QVBoxLayout(self.groupBox_fonts_message)
        self.layout_fonts_message.setContentsMargins(4, 4, 4, 4)
        self.layout_fonts_message.setSpacing(6)
        self.layout_fonts_message.setObjectName("layout_fonts_message")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_font_message_title = QtWidgets.QPushButton(parent=self.groupBox_fonts_message)
        self.pb_font_message_title.setObjectName("pb_font_message_title")
        self.horizontalLayout.addWidget(self.pb_font_message_title)
        self.pb_font_message_date = QtWidgets.QPushButton(parent=self.groupBox_fonts_message)
        self.pb_font_message_date.setObjectName("pb_font_message_date")
        self.horizontalLayout.addWidget(self.pb_font_message_date)
        self.pb_font_message_content = QtWidgets.QPushButton(parent=self.groupBox_fonts_message)
        self.pb_font_message_content.setObjectName("pb_font_message_content")
        self.horizontalLayout.addWidget(self.pb_font_message_content)
        self.layout_fonts_message.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox_fonts_message)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_fonts, "")

        # ── Advanced Tab ──
        self.tab_advanced = QtWidgets.QWidget()
        self.tab_advanced.setObjectName("tab_advanced")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_advanced)
        self.verticalLayout.setObjectName("verticalLayout")

        # Notifications group (moved from General)
        self.groupBox_notifications = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupBox_notifications.setObjectName("groupBox_notifications")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_notifications)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spin_priority = QtWidgets.QSpinBox(parent=self.groupBox_notifications)
        self.spin_priority.setMinimum(0)
        self.spin_priority.setMaximum(10)
        self.spin_priority.setProperty("value", 5)
        self.spin_priority.setObjectName("spin_priority")
        self.gridLayout_4.addWidget(self.spin_priority, 0, 1, 1, 1)
        self.label_notification_duration_ms = QtWidgets.QLabel(parent=self.groupBox_notifications)
        self.label_notification_duration_ms.setObjectName("label_notification_duration_ms")
        self.gridLayout_4.addWidget(self.label_notification_duration_ms, 1, 2, 1, 1)
        self.label_notification_priority = QtWidgets.QLabel(parent=self.groupBox_notifications)
        self.label_notification_priority.setObjectName("label_notification_priority")
        self.gridLayout_4.addWidget(self.label_notification_priority, 0, 0, 1, 1)
        self.cb_tray_icon_unread = QtWidgets.QCheckBox(parent=self.groupBox_notifications)
        self.cb_tray_icon_unread.setObjectName("cb_tray_icon_unread")
        self.gridLayout_4.addWidget(self.cb_tray_icon_unread, 4, 0, 1, 3)
        self.label_notification_duration = QtWidgets.QLabel(parent=self.groupBox_notifications)
        self.label_notification_duration.setObjectName("label_notification_duration")
        self.gridLayout_4.addWidget(self.label_notification_duration, 1, 0, 1, 1)
        self.cb_notification_click = QtWidgets.QCheckBox(parent=self.groupBox_notifications)
        self.cb_notification_click.setObjectName("cb_notification_click")
        self.gridLayout_4.addWidget(self.cb_notification_click, 3, 0, 1, 3)
        self.cb_notify = QtWidgets.QCheckBox(parent=self.groupBox_notifications)
        self.cb_notify.setObjectName("cb_notify")
        self.gridLayout_4.addWidget(self.cb_notify, 2, 0, 1, 3)
        self.spin_duration = QtWidgets.QSpinBox(parent=self.groupBox_notifications)
        self.spin_duration.setMinimum(500)
        self.spin_duration.setMaximum(30000)
        self.spin_duration.setSingleStep(100)
        self.spin_duration.setObjectName("spin_duration")
        self.gridLayout_4.addWidget(self.spin_duration, 1, 1, 1, 1)
        spacerItem_notif = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem_notif, 0, 2, 1, 1)
        self.groupBox_sound = QtWidgets.QGroupBox(parent=self.groupBox_notifications)
        self.groupBox_sound.setCheckable(True)
        self.groupBox_sound.setObjectName("groupBox_sound")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_sound)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_sound = QtWidgets.QLineEdit(parent=self.groupBox_sound)
        self.line_sound.setEnabled(True)
        self.line_sound.setReadOnly(True)
        self.line_sound.setObjectName("line_sound")
        self.gridLayout_5.addWidget(self.line_sound, 0, 0, 1, 1)
        self.pb_sound = QtWidgets.QPushButton(parent=self.groupBox_sound)
        self.pb_sound.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_sound.setObjectName("pb_sound")
        self.gridLayout_5.addWidget(self.pb_sound, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_sound, 5, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_notifications)

        # Settings group
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_reset = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_reset.setObjectName("pb_reset")
        self.horizontalLayout_2.addWidget(self.pb_reset)
        self.pb_import = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_import.setObjectName("pb_import")
        self.horizontalLayout_2.addWidget(self.pb_import)
        self.pb_export = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_export.setObjectName("pb_export")
        self.horizontalLayout_2.addWidget(self.pb_export)
        self.verticalLayout.addWidget(self.groupBox)

        # Image popup group
        self.groupbox_image_popup = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupbox_image_popup.setCheckable(True)
        self.groupbox_image_popup.setObjectName("groupbox_image_popup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupbox_image_popup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.groupbox_image_popup)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.spin_popup_w = QtWidgets.QSpinBox(parent=self.groupbox_image_popup)
        self.spin_popup_w.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spin_popup_w.setMinimum(100)
        self.spin_popup_w.setMaximum(10000)
        self.spin_popup_w.setObjectName("spin_popup_w")
        self.horizontalLayout_4.addWidget(self.spin_popup_w)
        self.label_2 = QtWidgets.QLabel(parent=self.groupbox_image_popup)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spin_popup_h = QtWidgets.QSpinBox(parent=self.groupbox_image_popup)
        self.spin_popup_h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spin_popup_h.setMinimum(100)
        self.spin_popup_h.setMaximum(10000)
        self.spin_popup_h.setObjectName("spin_popup_h")
        self.horizontalLayout_4.addWidget(self.spin_popup_h)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupbox_image_popup)

        # Watchdog group
        self.groupbox_watchdog = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupbox_watchdog.setCheckable(True)
        self.groupbox_watchdog.setObjectName("groupbox_watchdog")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupbox_watchdog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_watchdog_interval = QtWidgets.QLabel(parent=self.groupbox_watchdog)
        self.label_watchdog_interval.setObjectName("label_watchdog_interval")
        self.horizontalLayout_3.addWidget(self.label_watchdog_interval)
        self.spin_watchdog_interval = QtWidgets.QSpinBox(parent=self.groupbox_watchdog)
        self.spin_watchdog_interval.setMinimum(1)
        self.spin_watchdog_interval.setMaximum(100000)
        self.spin_watchdog_interval.setObjectName("spin_watchdog_interval")
        self.horizontalLayout_3.addWidget(self.spin_watchdog_interval)
        self.label_watchdog_interval_s = QtWidgets.QLabel(parent=self.groupbox_watchdog)
        self.label_watchdog_interval_s.setObjectName("label_watchdog_interval_s")
        self.horizontalLayout_3.addWidget(self.label_watchdog_interval_s)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupbox_watchdog)

        # Cache group
        self.groupBox_cache = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupBox_cache.setObjectName("groupBox_cache")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_cache)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_clear_cache = QtWidgets.QPushButton(parent=self.groupBox_cache)
        self.pb_clear_cache.setObjectName("pb_clear_cache")
        self.horizontalLayout_6.addWidget(self.pb_clear_cache)
        self.pb_open_cache_dir = QtWidgets.QPushButton(parent=self.groupBox_cache)
        self.pb_open_cache_dir.setObjectName("pb_open_cache_dir")
        self.horizontalLayout_6.addWidget(self.pb_open_cache_dir)
        self.label_cache = QtWidgets.QLabel(parent=self.groupBox_cache)
        self.label_cache.setObjectName("label_cache")
        self.horizontalLayout_6.addWidget(self.label_cache)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.groupBox_cache)

        # Logging group
        self.groupBox_logging = QtWidgets.QGroupBox(parent=self.tab_advanced)
        self.groupBox_logging.setObjectName("groupBox_logging")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_logging)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.combo_logging = QtWidgets.QComboBox(parent=self.groupBox_logging)
        self.combo_logging.setObjectName("combo_logging")
        self.gridLayout_6.addWidget(self.combo_logging, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(190, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 3, 1, 1)
        self.pb_open_log = QtWidgets.QPushButton(parent=self.groupBox_logging)
        self.pb_open_log.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_open_log.setObjectName("pb_open_log")
        self.gridLayout_6.addWidget(self.pb_open_log, 0, 2, 1, 1)
        self.label_logging = QtWidgets.QLabel(parent=self.groupBox_logging)
        self.label_logging.setObjectName("label_logging")
        self.gridLayout_6.addWidget(self.label_logging, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_logging)

        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.tabWidget.addTab(self.tab_advanced, "")

        # ── Bottom bar ──
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 5)
        self.label_qt_icon = QtWidgets.QLabel(parent=Dialog)
        self.label_qt_icon.setText("")
        self.label_qt_icon.setObjectName("label_qt_icon")
        self.gridLayout.addWidget(self.label_qt_icon, 1, 2, 1, 1)
        self.label_app_version = QtWidgets.QLabel(parent=Dialog)
        self.label_app_version.setText("")
        self.label_app_version.setObjectName("label_app_version")
        self.gridLayout.addWidget(self.label_app_version, 1, 1, 1, 1)
        self.label_app_icon = QtWidgets.QLabel(parent=Dialog)
        self.label_app_icon.setText("")
        self.label_app_icon.setObjectName("label_app_icon")
        self.gridLayout.addWidget(self.label_app_icon, 1, 0, 1, 1)
        self.label_qt_version = QtWidgets.QLabel(parent=Dialog)
        self.label_qt_version.setText("")
        self.label_qt_version.setObjectName("label_qt_version")
        self.gridLayout.addWidget(self.label_qt_version, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        # General tab
        self.groupBox_2.setTitle(tr("settings.interface"))
        self.label_language.setText(tr("settings.interface.language"))
        self.label_3.setText(tr("settings.interface.style"))
        self.cb_priority_colors.setToolTip(tr("settings.interface.priority_colors.tooltip"))
        self.cb_priority_colors.setText(tr("settings.interface.priority_colors"))
        self.cb_image_urls.setText(tr("settings.interface.image_urls"))
        self.cb_locale.setText(tr("settings.interface.locale"))
        self.cb_sort_applications.setText(tr("settings.interface.sort_apps"))
        self.cb_autostart.setText(tr("settings.interface.autostart"))
        self.groupBox_server_info.setTitle(tr("settings.server_info"))
        self.pb_change_server_info.setText(tr("settings.server_info.change"))
        self.groupBox_topics_api.setTitle(tr("settings.topics_api"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), tr("settings.tab.general"))

        # Fonts tab
        self.pb_reset_fonts.setText(tr("settings.fonts.reset_all"))
        self.groupBox_fonts_message.setTitle(tr("settings.fonts.message"))
        self.pb_font_message_title.setText(tr("settings.fonts.title"))
        self.pb_font_message_date.setText(tr("settings.fonts.date"))
        self.pb_font_message_content.setText(tr("settings.fonts.message_btn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fonts), tr("settings.tab.fonts"))

        # Advanced tab
        self.groupBox_notifications.setTitle(tr("settings.notifications"))
        self.label_notification_duration_ms.setText(tr("settings.notifications.duration.ms"))
        self.label_notification_priority.setText(tr("settings.notifications.priority"))
        self.cb_tray_icon_unread.setText(tr("settings.notifications.tray_unread"))
        self.label_notification_duration.setText(tr("settings.notifications.duration"))
        self.cb_notification_click.setText(tr("settings.notifications.click"))
        self.cb_notify.setText(tr("settings.notifications.missed"))
        self.groupBox_sound.setTitle(tr("settings.notifications.sound"))
        self.pb_sound.setToolTip(tr("settings.notifications.sound.choose"))
        self.pb_sound.setText("...")
        self.groupBox.setTitle(tr("settings.advanced.settings"))
        self.pb_reset.setText(tr("settings.advanced.reset"))
        self.pb_import.setText(tr("settings.advanced.import"))
        self.pb_export.setText(tr("settings.advanced.export"))
        self.groupbox_image_popup.setTitle(tr("settings.advanced.image_popup"))
        self.label.setToolTip(tr("settings.advanced.image_popup.width.tooltip"))
        self.label.setText(tr("settings.advanced.image_popup.width"))
        self.spin_popup_w.setToolTip(tr("settings.advanced.image_popup.width.tooltip"))
        self.label_2.setToolTip(tr("settings.advanced.image_popup.height.tooltip"))
        self.label_2.setText(tr("settings.advanced.image_popup.height"))
        self.spin_popup_h.setToolTip(tr("settings.advanced.image_popup.height.tooltip"))
        self.groupbox_watchdog.setTitle(tr("settings.advanced.watchdog"))
        self.label_watchdog_interval.setText(tr("settings.advanced.watchdog.interval"))
        self.label_watchdog_interval_s.setText(tr("settings.advanced.watchdog.s"))
        self.groupBox_cache.setTitle(tr("settings.advanced.cache"))
        self.pb_clear_cache.setText(tr("settings.advanced.cache.clear"))
        self.pb_open_cache_dir.setText(tr("settings.advanced.cache.open"))
        self.label_cache.setText("0 MB")
        self.groupBox_logging.setTitle(tr("settings.advanced.logging"))
        self.pb_open_log.setToolTip(tr("settings.advanced.logging.open"))
        self.pb_open_log.setText("...")
        self.label_logging.setText(tr("settings.advanced.logging.level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), tr("settings.tab.advanced"))

        # Dialog buttons
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setText(tr("button.ok"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Cancel).setText(tr("button.cancel"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Apply).setText(tr("button.apply"))
